SOURCES = \
	main.c \
	../lib/vdp.c \
	../lib/vdp_print.c \
	../lib/copper.c \
	../lib/assert.c \
	../lib/math_util.c \
	../common/font.c \
	../common/tinyprintf.c

OPT_LEVEL := -O3

include ../common/core.mk

