SOURCES = \
	main.c \
	../lib/vdp.c \
	../lib/vdp_print.c \
	../lib/copper.c \
	../lib/assert.c \
	../lib/math_util.c \
	../common/vectors.S \
	../common/start.S \
	../common/font.c \
	../common/tinyprintf.c

HEADERS = \
	../lib/vdp.h \
	../lib/vdp_print.h \
	../lib/math_util.h \
	../lib/assert.h \
	../lib/copper.h \
	../common/font.h \
	../common/tinyprintf.h

OPT_LEVEL := -O3

include ../common/common.mk
