SOURCES = \
	main.c \
	../lib/vdp.c \
	../lib/copper.c \
	../lib/assert.c \
	../common/vectors.S \
	../common/start.S

HEADERS = \
	../lib/vdp.h \
	../lib/assert.h \
	../lib/copper.h

include ../common/common.mk
